export const iiqaData = {
  affiliatingUniversity: "Affiliating University",
  alternateEmail: "Alternate Email",
  alternateFacultyAddress: "Alternate Faculty Address",
  alternateFacultyAltenateEmail: "Alternate Faculty Alternate Email",
  alternateFacultyDesignation: "Alternate Faculty Designation",
  alternateFacultyEmail: "Alternate Faculty Email",
  alternateFacultyFax: "Alternate Faculty Fax",
  alternateFacultyFaxAreaCode: "Alternate Faculty Fax Area Code",
  alternateFacultyMobile: "Alternate Faculty Mobile",
  alternateFacultyName: "Alternate Faculty Name",
  alternateFacultyPhone: "Alternate Faculty Phone",
  alternateFacultyPhoneAreaCode: "Alternate Faculty Phone Area Code",
  alternateFacultyPincode: "Alternate Faculty Pincode",
  city: "City",
  collegeAddress: "College Address",
  collegeFax: "College Fax",
  collegeFaxAreaCode: "College Fax Area Code",
  collegePhone: "College Phone",
  collegePhoneAreaCode: "College Phone Area Code",
  collegePincode: "College Pincode",
  collegeRegistrationId: "College Registration ID",
  collegeWebsite: "College Website",
  completed: "Completed",
  cycleOfAccreditation: "Cycle Of Accreditation",
  dateOfEstablishmentOfIQACorCIQA: "Date Of Establishment Of IQACorCIQA",
  dateOfGeneralDevelopementGrant: "Date Of General Development Grant",
  dateOfRecognitionByUGC_12B: "Date Of Recognition By UGC 12B",
  dateOfRecognitionByUGC_2f: "Date Of Recognition By UGC 2f",
  dateOf_AISHE_Upload: "Date Of AISHE Upload",
  date_of_establishment_of_the_Institution:
    "Date Of Establishment Of The Institution",
  designation: "Designation",
  district: "District",
  documentAISHE_Upload_Date: "Document AISHE Upload Date",
  documentCertification_by_Head_of_the_Institution:
    "Document Certification By Head Of The Institution",
  documentOfRecognisedAsCPE: "Document Of Recognised As CPE",
  documentOfRecognisedAutonomous: "Document Of Recognised Autonomous",
  documentOfRecognitionByUGC_12B: "Document Of Recognition By UGC 12B",
  documentOfRecognitionByUGC_2f: "Document Of Recognition By UGC 2f",
  documentRecognisedAsCollege_of_Excellence:
    "Document Recognised As College Of Excellence",
  document_academic_mou_foreign: "Document Academic MOU Foreign",
  documentofAISHE_MHRD: "Document Of AISHE MHRD",
  does_StatutoryCommitteesExist: "Does Statutory Committees Exist",
  headOfTheInstitution: "Head Of The Institution",
  iiqa_ID: "IIQA ID",
  institutionRecognisedAsCPE: "Institution Recognised As CPE",
  institutionRecognisedAsCollege_of_Excellence:
    "Institution Recognised As College Of Excellence",
  institutionRecognisedAutonomous: "Institution Recognised Autonomous",
  institutionisRegistereNAD_Document: "Institution Is Registered NAD Document",
  isAffiliated: "Is Affiliated",
  isCollegeFunctionFromOwnCampus: "Is College Function From Own Campus",
  isInstitutionRecognisedAutonomous: "Is Institution Recognised Autonomous",
  isSpecificTypeOfCollege: "Is Specific Type Of College",
  nameOfHigherEducationInstitution: "Name Of Higher Education Institution",
  natureOfCollegeConstitiuent: "Nature Of College Constituent",
  natureOfCollegeGoverment: "Nature Of College Government",
  natureOfCollegeGrantAid: "Nature Of College Grant Aid",
  natureOfCollegePrivate: "Nature Of College Private",
  natureOfCollegeSelfFinancing: "Nature Of College Self Financing",
  program_Count_Certificate_Awareness: "Program Count Certificate Awareness",
  program_Count_DM_Ayurveda_Vachaspathi:
    "Program Count DM Ayurveda Vachaspathi",
  program_Count_Diploma: "Program Count Diploma",
  program_Count_Doctoral: "Program Count Doctoral",
  program_Count_PG: "Program Count PG",
  program_Count_PG_Diploma: "Program Count PG Diploma",
  program_Count_Post_Doctoral: "Program Count Post Doctoral",
  program_Count_Pre_Doctoral: "Program Count Pre Doctoral",
  program_Count_UG: "Program Count UG",
  rtiactSection4_1_b_Declaration_Url: "RTI Act Section 4 1 b Declaration URL",
  selfDeclaration: "Self Declaration",
  stateOrUT: "State Or UT",
  statutoryCommittees_for_Anti_ragging: "Statutory Committees For Anti Ragging",
  statutoryCommittees_for_Grievance_Redressal:
    "Statutory Committees For Grievance Redressal",
  statutoryCommittees_for_Internal_Compliant:
    "Statutory Committees For Internal Compliant",
  statutoryCommittees_for_MinorityCell:
    "Statutory Committees For Minority Cell",
  statutoryCommittees_for_OBC_cell: "Statutory Committees For OBC Cell",
  statutoryCommittees_for_ST_SC: "Statutory Committees For ST SC",
  verified: "Verified",
  years_of_graduation_of_the_last_two_batches:
    "Years Of Graduation Of The Last Two Batches",
};

export const ssrData = {
  "Built-up Area (in Sq. Mt)": "builtUpAreaInSqMt",
  "Type Of the Institution by Gender": "byGender",
  "Type Of the Institution by Shift": "byShift",
  "Campus Area (in Acres)": "campusAreaInAcres",
  "Campus Location": "campusLocation",
  "College Autonomous Application Status": "collegeAutonomousApplicationStatus",
  "College ID": "collegeID",
  "Date of Recognition": "dateOfRecognisation",
  "Document of Minority Institution": "documentOFMinorityInstitution",
  "Is Autonomy Granted": "isAutonomyGranted",
  "Is Autonomy Granted Document": "isAutonomyGrantedDocumnet",
  "Is College Recognized by Govt Agency": "isCollegeRecognizedByGovtAgency",
  "Minority by Linguistic": "minorityByLinguistic",
  "Minority by Other": "minorityByOther",
  "Minority by Religious": "minorityByReligious",
  "Prepare IIQA ID": "prepareIIQAID",
  "Recognized Agency Name": "recognizedAgencyName",
  "Recognized Minority Institution": "recognizedMinorityInstitution",
  Remarks: "remarks",
  "SSR ID": "ssrID",
};
